### ISSUE TITLE
The script mutes downloaded fiiles as well.

### ISSUE THREAD

**Issue by leronOthesideofEggs** [gdi3d/mute-spotify-ads-mac-osx#11]
I would love to have this script unmute downloaded files and music as well that I added personally into music.

In Spotify you can add songs to your playlist from your local files. I hope you understand what I mean. I guess the script also detects that the downloaded file is not a song so it mutes the audio.Idk how long this script was made ago. sooooo id be happy to get a reply because I always use this script when i open Spotify :))))

**Comment by gdi3d** [comment]
Since I'm using the free version of Spotify I've never used that option.

But I would research about what's happening and ask for your help in a few days if that's ok with you.

**Comment by hrvstr** [comment]
It is possible to use this feature with a free account. I just tested it. You can add a folder in the settings.

![Bildschirmfoto 2021-06-11 um 09 23 59](https://user-images.githubusercontent.com/4610008/121647894-313ebe00-ca97-11eb-8c8e-a74c05828ae0.png)

**Comment by gdi3d** [comment]
I've run some tests and it works fine except when your file doesn't have the album name set.

The script detects an Ad by checking a few things, among those things is the albumName property. If that property is empty then is flagged as an Ad and the volume is muted. So it's working as expected.

I'm closing the ticket since it's not really a bug. Thanks for your contribution anyways 🤗.

**Comment by leronOthesideofEggs** [comment]
Oooh okay :O  much thankss for the reply and feedback :)))
