### ISSUE TITLE
Delayed muting & unmuting

### ISSUE THREAD

**Issue by Fyrelite** [gdi3d/mute-spotify-ads-mac-osx#22]
Whenever an ad plays, occasionally it works properly and mutes the ad, but most of the time for me there is a 1 to 5 second delay before the ad is muted, and a similar delay before the audio is unmuted. Sometimes it fails to mute an ad completely and I have to restart it from the terminal to get it working again.

**Comment by gdi3d** [comment]
If you're using an older os version (catalina and before) the delay can happen because of how the script works. There's nothing else I can do right now to prevent that.

If you're not using a catalina or a previous version, please let me know what version you're using so I can test it with that specific version.

You can run this command on the console to find out the version:
`defaults read loginwindow SystemVersionStampAsString`

About some ads not being muted at all, that's a know issue because some of the ads (a very low % in my experience) doesn't work in the same way as the majority of them, so it becomes imposible to detect them in the current design.

**Comment by gdi3d** [comment]
Closing ticket due to lack of response

**Comment by Fyrelite** [comment]
Ah I see, I am using Catalina, however on a separate note would you be
interested in working on a script that automatically skips the ads after 5
seconds?

**Comment by gdi3d** [comment]
It can't be done with the current method, sorry.
