### ISSUE TITLE
Volume level constantly decreases

### ISSUE THREAD

**Issue by sunabozu** [gdi3d/mute-spotify-ads-mac-osx#25]
I've had this problem for a very long time on different devices and macOS versions. When the script is running, no matter how many times I set the volume at 50%, it keeps falling back to somewhere around 40% after each song. I does it in a few steps from what I see, very quickly.
I can't be the only one who experiences this, right?

**Comment by gdi3d** [comment]
I was able to reproduce the error. It doesn't happen if the volumen is set a 100%.

Not sure if I can solve the bug entirely, but at least I can try to avoid that dropping of 10%.

I will be working on this ASAP.

Thanks for the report 😉

**Comment by gdi3d** [comment]
I was able to fix it. The bug was causing the volume to drop 1 point every now and then, specially when changing to a new song.

Please update the script with the autoupdate feature by just running the script again and when asked to update the script select `Y`.

Close the ticket if the everything is working properly.

**Comment by sunabozu** [comment]
Seems to be working seamlessly. Thank you!
