### ISSUE TITLE
Crash with stats.txt

### ISSUE THREAD

**Issue by chr0max** [gdi3d/mute-spotify-ads-mac-osx#43]
I often have a crash of the script and this:
cat: MuteSpotifyAds/stats.txt: No such file or directory

So maybe there should be an option for stats, I don`t need that.

**Comment by gdi3d** [comment]
Hey @chr0max, thanks for reporting.

The **stats.txt** file should be created automatically if it doesn't exists.

Can you provide some information to help me debug?:

- Did you ever set the env var **MUTE_SPOTIFY_STATS_PATH** ?
- Is the directory where you installed the script protected against write (maybe created with other user)?

I'm going to evaluate the option to disable stats since it makes sense for some user I guess.

**Comment by gdi3d** [comment]
Close due to inactivity
